#!/usr/bin/env python3
"""Prepare the approved static website for Cloudflare Pages; no dependencies."""
from __future__ import annotations

import hashlib
import json
import shutil
import stat
import sys
import tempfile
import zipfile
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parents[1]
MARKER = ".sevarel-generated-output"


def prepare(root: Path = ROOT) -> int:
    config = json.loads((root / "deploy-manifest.json").read_text(encoding="utf-8"))
    name = config["archive"]
    if Path(name).name != name:
        raise ValueError("The archive must be a file in the repository root.")
    archive = root / name
    if not archive.is_file():
        raise FileNotFoundError(
            f"Hosting-Datei fehlt: {name}. Diese ZIP unveraendert in das "
            "GitHub-Repository hochladen (Add file > Upload files), dann erneut deployen."
        )
    if hashlib.sha256(archive.read_bytes()).hexdigest() != config["sha256"]:
        raise ValueError("Falsche oder veraenderte Hosting-ZIP: SHA-256 stimmt nicht ueberein.")
    if config["output"] != "website":
        raise ValueError("Only the generated website/ directory may be written.")
    output = root / "website"
    marker = root / MARKER
    if output.is_symlink():
        raise ValueError("Output must not be a symbolic link.")
    if output.exists() and not marker.is_file():
        raise ValueError("website/ already exists and is not marked as generated; refusing to overwrite.")

    with tempfile.TemporaryDirectory(prefix="sevarel-build-", dir=root) as temp:
        staging = Path(temp) / "website"
        staging.mkdir()
        with zipfile.ZipFile(archive) as bundle:
            entries = bundle.infolist()
            files = [entry for entry in entries if not entry.is_dir()]
            if len(files) != config["files"]:
                raise ValueError("Unexpected file count.")
            if sum(entry.file_size for entry in files) > 64 * 1024 * 1024:
                raise ValueError("Uncompressed archive exceeds the safety limit.")
            names = set()
            for entry in entries:
                path = PurePosixPath(entry.filename)
                if (path.is_absolute() or ".." in path.parts or not path.parts
                        or "\\" in entry.filename or ":" in entry.filename):
                    raise ValueError(f"Unsafe archive path: {entry.filename}")
                if entry.filename in names:
                    raise ValueError("Duplicate archive entry.")
                names.add(entry.filename)
                mode = entry.external_attr >> 16
                if stat.S_ISLNK(mode) or entry.flag_bits & 1:
                    raise ValueError("Links and encrypted entries are not allowed.")
                if entry.is_dir():
                    continue
                if entry.file_size >= 25 * 1024 * 1024:
                    raise ValueError("An asset exceeds the allowed file size.")
                if path.suffix.lower() in {".ttf", ".otf", ".woff", ".woff2", ".pem", ".key"}:
                    raise ValueError("Unexpected font or key file in public output.")
                if any(part.startswith(".env") or part == ".git" for part in path.parts):
                    raise ValueError("Private configuration must not be published.")
                destination = staging.joinpath(*path.parts)
                destination.parent.mkdir(parents=True, exist_ok=True)
                # ZipFile.read also checks each member's CRC.
                destination.write_bytes(bundle.read(entry))

        required = ["index.html", "404.html", "_headers", "_redirects", "robots.txt", "assets/site.css"]
        for relative in required:
            if not (staging / relative).is_file():
                raise ValueError(f"Missing required public file: {relative}")
        pages = list(staging.rglob("*.html"))
        if len(pages) != config["html_pages"]:
            raise ValueError("Unexpected number of HTML pages.")
        if "noindex" not in (staging / "_headers").read_text(encoding="utf-8"):
            raise ValueError("The approved preview must remain noindex.")
        contact = (staging / "kontakt/index.html").read_text(encoding="utf-8")
        if 'data-mode="draft"' not in contact:
            raise ValueError("The approved contact form must remain in local draft mode.")

        if output.exists():
            shutil.rmtree(output)
        staging.rename(output)
        marker.write_text("Generated by scripts/prepare_cloudflare.py\n", encoding="utf-8")
    print(f"SEVAREL Consulting {config['version']}: {len(files)} Dateien / {len(pages)} HTML-Seiten in website/.")
    print("Originaldateien unveraendert; Vorschau/noindex und lokaler Anfragebrief bleiben aktiv.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(prepare())
    except (OSError, ValueError, KeyError, zipfile.BadZipFile) as error:
        print(f"Build abgebrochen: {error}", file=sys.stderr)
        raise SystemExit(1)
